variable "access_key" {}
variable "secret_key" {}
variable "region" {}
variable "zone" {}
variable "ssh_ip" {}
variable "public_key_location" {}
variable "image_name" {}
variable "instance_type" {}
variable "prefix" {}
variable "vpc_cidr_block" {}
variable "subnet_cidr_block" {}
